### PR TITLE
Make OpenFace work with Python 3

### PR DESCRIPTION
**Pull request by qacollective**
### What does this PR do?
Makes multiple small changes to python code to make it run on Python 3, while retaining compatibility with Python 2.7.

### Where should the reviewer start?
Look at the GitHub change comparison (diff) screen, most changes are very minor.  I've made changes to all code that I could find which was incompatible, including code which is currently commented out.

### How should this PR be tested?
Run ./run-tests.sh on a Python 2.7 OpenFace environment.

**Note:** there is an issue that the test scripts explicitly refer to the version of Python to run.  In this PR, I've simply updated strings 'python2' to 'python3' and am unsure how to make this more parameterised with nosetests in front (nose doesn't seem to be able to pass parameters and I didn't want to duplicate all tests-one set for each python version!).

### Any background context you want to provide?
I have only tested these changes in a docker image built in a Python 3.5, Dlib 19.2 and OpenCV 3.2 environment.  This environment is built by a docker file that I am yet to send through in a subsequent pull request.  So I have not yet been able to validate backwards compatibility.  I have however made all code changes after verifying that the change is backwards compatible in a Python 2.7 console.

The output I received is linked below, but all failures appear due to different base library versions (to be discussed?).
https://github.com/cmusatyalab/openface/files/735177/OpenFace_Python3_Test_Output.txt

### What are the relevant issues?
#172 

# Questions:

+ Do the docs need to be updated?
No

+ Does this PR add new (Python) dependencies?
No

### CODE REVIEW

**Comment by bamos** [comment]
Hi, thanks for sending in the changes to add Python 3 support a while ago. I'm merging this now and adding some further additions to the master branch so that the code's compatible with Python 2 and 3.

-Brandon.

**Comment by PrimozGodec** [comment]
Thank you for making Python 3 support available. 
Current docker image `cbwang/ubuntu-opencv-dlib-torch` still uses Python 2. Is there any new image that would use Python 3?

**Comment by PrimozGodec** [comment]
@bamos with this PR the support for Python3 was added. Is there any instruction on what to install in case we want to use python3?

**Comment by PrimozGodec** [comment]
@qacollective is that possible that you share the Python 3 docker file you used for testing if you still have it anywhere?

**Comment by Chappie74** [comment]
Any update on this? Is there a docker file for the python3 version?

**Comment by mlensment** [comment]
+1 for Dockerfile example.

**Comment by rohit7044** [comment]
I don't see the setup steps for python 3. Can anyone kindly lead me to it. Cause the pickle gives me version mismatch error.If there's anyone who installed it in python 3.6+ please lmk

**Pull request merged**
