### PR TITLE
Replace sanitize by clearState()

### PR DESCRIPTION
**Pull request by melgor**
### What does this PR do?
Replace sanitize function by clearState() delivered by Torch

### What are the relevant issues?
#106 

# Questions:
@bamos 
I tested it using nn4.small2 model
Sanitize: 170 Mb
clearState: 101 Mb

The model delivered by you have only 30 Mb. I get back to commit before adding 'cudnn.convert' and here model use only 30 Mb (Threre I tested clearState and produce the model with similar number of Mb).  So #108 add some bug at saving modules (neither Sanitize nor clearState clear all buffers). I want to start with the easiest part of new features, but now I have trouble in each of them....

### CODE REVIEW

**Comment by bamos** [comment]
Hi @melgor - interesting! Too bad these features weren't as easy as we thought. I wonder if there's an easy way to dump out the memory buffers that each module is using. Maybe by modifying Torch's `File:writeObject`? https://github.com/torch/torch7/blob/1cf98511b39a486f74aa4ecce02f8de422101a2d/File.lua#L107

-Brandon.

**Comment by melgor** [comment]
I found the reason of this situation. I just print
```lua
model:listModules()
```
and it gives me each modules with theirs buffers and matrix in it. This let me see what buffer are not empty.
'gradWeight','gradBias' - removing them from nn4.small2 reduce size by 13 MB. These buffers where mostly in BN and CONV layers
'_gradOutput' - removing it reduce size by next 73 Mb. These buffers where mostly in ReLU layers

So, final model have only ~15 Mb. You can test such sanitize if models still works ok by replacing in [sanitize.lua](https://github.com/cmusatyalab/openface/blob/master/training/sanitize.lua#L8)
```lua
local common = {'output', 'gradInput'}
```
by 
```lua
local common = {'output', 'gradInput','buffer','gradWeight','gradBias','_gradOutput'}
```
So, I think that this is problem related to Torch. This buffers should be at their "clearState" function.
But there is another problem:) ex.nn.ReLU and cudnn.ReLU will have different "clearState" implementation, so nn.ReLU:clearState() will not clear the buffers from cudnn version

So, @bamos Will we merge it now and wait until Torch dev will fix it or we will now just add some parameters to "sanitize" and stay with it (which may be better to get smaller models)?

**Comment by fmassa** [comment]
@melgor one can't simply remove those `gradWeight` and `gradBias` buffers in `clearState`, as they are needed for training and are not reconstructed in the forward/backward passes. They enter in another category actually, as you usually call `:getParameters` before training, and that requires one to have the `gradWeight`/`gradBias` already initialized.
There are some alternatives, as writing a function like [`:unpack`](https://gist.github.com/szagoruyko/2831b1ab990bb24ade14) or [here](https://github.com/fmassa/optimize-net/blob/master/init.lua#L226-L236) and calling the functions uppon loading from disk, but they don't yet handle shared gradients.

About the difference in the `clearState` from `nn` and `cudnn`, this is actually not a problem, as during the conversion [the cudnn descriptors are cleared](https://github.com/soumith/cudnn.torch/blob/master/convert.lua#L44)

**Comment by bamos** [comment]
@melgor - great to know `:listModules` prints the buffers, and that you were able to trim the size from 100mb to 15mb.

@fmassa - thanks for commenting on these with the helpful advice.

Let's use `clearState` for now without deleting the buffers needed in training. When I plan to release a new model I'll manually chop all of the training buffers for the default model since most people won't use it in training mode and I'll also release the full training model.

**Pull request merged**
